add fallback categories, add fallback search cache generator, remove WMA, minor fixes

diff --git a/extra/abs/get_iplayer-patched-git/PKGBUILD b/extra/abs/get_iplayer-patched-git/PKGBUILD
--- a/extra/abs/get_iplayer-patched-git/PKGBUILD
+++ b/extra/abs/get_iplayer-patched-git/PKGBUILD
@@ -8,33 +8,48 @@
 #pkgname=get_iplayer-git
 pkgname=get_iplayer-patched-git
 
-pkgver=r673.a95ca65
-pkgrel=1
-pkgdesc="Allows you to download or stream any iPlayer programme from the BBC in H.264 (Quicktime/mp4) format, any radio programmes in MP3 or RealAudio format"
+pkgver=2.91
+pkgrel=2
+pkgdesc="Download TV and radio from BBC iPlayer"
 arch=('any')
-url="http://www.infradead.org/get_iplayer/html/get_iplayer.html"
+url="https://github.com/get-iplayer/get_iplayer"
 license=('GPL3')
-depends=('perl-libwww' 'perl-html-parser' 'perl-www-mechanize' 'perl-http-cookies' 'perl-net-http')
+#  'perl-json: metadata parsing'
+#  'perl-xml-simple: metadata parsing'
+depends=('perl-html-parser' 'perl-http-cookies' 'perl-libwww' 'perl-net-http' 'perl-www-mechanize')
+#  'perl-net-smtps: Mail search results via TLS (alternative)'
 optdepends=(
-  'rtmpdump: record high-quality flash-based content'
-  'flvstreamer: download files that are in flash (flv) format'
-  'ffmpeg: convert flash (flv) files'
-  'atomicparsley: add tags to MP4 files'
-  'id3v2: add basic tags to MP3 files (if perl-mp3-tag not installed)'
-  'lame: re-encode Real files into MP3'
-  'mplayer: download files that are in Real or WMA format'
-  'perl-mp3-tag: add tags to MP3 files'
-  'perl-xml-simple: Series and Brand pid parsing'
-  'vlc: download files in that are n95 format')
+  #'atomicparsley: MP4 and M4A files metadata tagging. Newer "atomicparsley-largefile-hg" is preferred'
+  #
+  # Having only 'optdepends atomicparsley' is sufficient to install either atomicparsley or atomicparsley-largefile-hg.
+  # However, added 'optdepends atomicparsley-largefile-hg' so 'pacman -Qi' will show 'atomicparsley-largefile-hg [installed]'
+  'atomicparsley: MP4 and M4A files metadata tagging'
+  'atomicparsley-largefile-hg: MP4 and M4A files metadata tagging (preferred)'
+
+  'ffmpeg: FLV files to MP4, M4A, MP3 or AVI files'
+  'flvstreamer: Flash audio/video streams to FLV files. An "rtmpdump" alternative'
+  'id3v2: MP3 files metadata tagging. Alternative "perl-mp3-tag" is preferred (full ID3 tagging)'
+  'lame: MP3 encoder'
+  'mplayer: FLV files to MP3 files. Windows Media audio streams to WMA files'
+  'perl-authen-sasl: Mail search results via SSL'
+  'perl-mp3-info: Catalogue MP3 files in localfiles plugin'
+  'perl-mp3-tag: MP3 files metadata tagging'
+  'perl-net-smtp-ssl: Mail search results via SSL'
+  'perl-net-smtp-tls: Mail search results via TLS'
+  'perl-xml-simple: metadata parsing'
+  'rtmpdump: Flash audio/video streams to FLV files'
+  'vlc: 3gp / N95 h.264 streams')
 makedepends=('git')
 conflicts=('get_iplayer')
 provides=('get_iplayer')
-source=($pkgname::git://git.infradead.org/get_iplayer.git)
+#source=($pkgname::git://git.infradead.org/get_iplayer.git)
+source=($pkgname::git://github.com/get-iplayer/get_iplayer.git)
 md5sums=(SKIP)
 
 pkgver() {
   cd $pkgname
-  printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
+  #printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
+  git describe --match "v*" --tags | sed -r 's/^v//;s/([^-]*-g)/r\1/;s/-/./g'
 }
 
 #PATCH
@@ -65,21 +80,26 @@ build() {
   # Patch: disable Akamai
   sed -i "s|\(^[ \t]*\)\(if ( \$cattribs->{kind} eq 'akamai' ) {.*\)|\n\1#PATCH\n\1#\2\n\1if ( \$cattribs->{kind} eq 'DISABLED_akamai' ) {\n|" get_iplayer
 
+  # Radio categories in search results
+  #NOTE Or use --refresh-feeds=ion (listview feed) or --refresh-feeds=ion2 (atoz feed)
+  sed -i "s|\(^[ \t]*\)\(.*\)\(\$self->get_links_aod\)\(.*\)|\1#PATCH\n\1#\2\3\4\n\1\2\$self->get_links_ion\4|" get_iplayer
+
   # Check applied patches
-  if [ $(grep "#PATCH" get_iplayer | wc -l) -ne 4 ]; then
-    echo "ERROR: the number of lines patched in /usr/bin/get_iplayer is different than expected" >&2
+  if [ $(grep "#PATCH" get_iplayer | wc -l) -ne 5 ]; then
+    echo "  -> ERROR: the number of lines patched in /usr/bin/get_iplayer is different than expected" >&2
   fi
 }
 
 package() {
   cd $pkgname
-  install -m755 -D get_iplayer "$pkgdir/usr/bin/get_iplayer"
-  install -m644 -D README.md "$pkgdir/usr/share/doc/get_iplayer/README.md"
-  install -m644 -D get_iplayer.1 "$pkgdir/usr/share/man/man1/get_iplayer.1"
+  install -Dm755 get_iplayer "$pkgdir/usr/bin/get_iplayer"
+  install -Dm755 get_iplayer.cgi "$pkgdir/usr/bin/get_iplayer.cgi"
 
-  install -m755 -d "$pkgdir/usr/share/get_iplayer/plugins"
-  install -m644 plugins/*.plugin "$pkgdir/usr/share/get_iplayer/plugins/"
-  install -m755 plugins/plugin.template "$pkgdir/usr/share/get_iplayer/plugins/"
-  install -m755 plugins/plugin.template "$pkgdir/usr/share/get_iplayer/plugins/"
+  install -Dm644 README.md "$pkgdir/usr/share/doc/get_iplayer/README.md"
+
+  install -Dm644 get_iplayer.1 "$pkgdir/usr/share/man/man1/get_iplayer.1"
+
+  install -dm755 "$pkgdir/usr/share/get_iplayer/plugins"
+  install -m644 plugins/*.plugin plugins/plugin.template "$pkgdir/usr/share/get_iplayer/plugins/"
 }
 
